Squashed 'src/bitshuffle/' changes from a60471d3..b9a15461
b9a15461 Don't build on 3.11 for macOS as there is no h5py build
85729f43 Bump bitshuffle version number
ea8a692e Ensure zstd options are added to filter build
21ecaaea Add the CPATH to cibw
eebf617c Update README to add caveats about the binary wheels
c8f05ad5 Restrict binary wheels to x86_64 Haswell builds
71a7bebe Allow setting of architecture without requiring an OpenMP build
330cf900 Allow setting build architecture by environment variable
c1d53f6c Bump pypa/gh-action-pypi-publish from 1.4.2 to 1.5.1
a599038e Bump pypa/cibuildwheel from 2.3.1 to 2.11.2
30b52c3e Add info about the hdf5 bitsuffle Rust plugin into README
07c72656 ci: Automatically update GitHub Actions in the future
3ff41af9 ci: Update GitHub Actions
8df4c178 Fix typos (#124)
881f97a3 Fix build error C2036 on Windows
61c65ae9 Check for HDF5 headers
982f8fec Allow installation without HDF5 libraries on the system
fdfcd404 AVX512 support (#117)

git-subtree-dir: src/bitshuffle
git-subtree-split: b9a1546133959298c56eee686932dbb18ff80f7a